name: Funny Comment on PR Creation

on:
  pull_request:
    types:
      - opened
  issues:    

jobs:
  send_funny_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Send Funny Comment on PR Creation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          comment_message="🎉 Congratulations on creating a new pull request! This is going to be LEGENDARY! 🚀"
          echo "$comment_message" | gh pr comment ${{ github.event.pull_request.number }} -R ${{ github.repository }}
