name: JAI CODING CLUB

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: greet
      run: echo "thanks for sharing!"    
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "THANKS FOR SHARING YOUR ISSUE . WILL LOOK INTO THE PROBLEM SOON."
        pr-message: "THANKS FOR CONTRIBUTING 👍. WILL LOOK INTO THE PR SOON."
 
  
