name: Send PR Created Message

on:
  pull_request:
    types:
      - opened
  issues:    

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: new
        uses: actions/checkout@v2
        with:
          title: New PR Created
          message: |
            A new pull request has been created:
            - Repository: ${{ github.repository }}
            - Author: ${{ github.event.pull_request.user.login }}
            - Title: ${{ github.event.pull_request.title }}
            - URL: ${{ github.event.pull_request.html_url }}
